### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [yanna1986/29-08-2020#1]
1)
видео недоступно
2)
скруглений нет
![image](https://user-images.githubusercontent.com/8464662/92311662-a689d980-efc1-11ea-90a4-8f5b05238aba.png)

3)
отступов нет
![image](https://user-images.githubusercontent.com/8464662/92311669-b6a1b900-efc1-11ea-98ec-0abf26bd76bc.png)

4)
код невалиден на двух страницах
![image](https://user-images.githubusercontent.com/8464662/92311673-c7eac580-efc1-11ea-9a59-bdfcf561b014.png)

5)
поскольку работа сдается, рабочие комментарии следует удалить.

**Comment by yanna1986** [comment]
https://github.com/yanna1986/29-08-2020
https://yanna1986.github.io/29-08-2020/
Добрый вечер

сб, 5 сент. 2020 г. в 21:52, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
3 - не все исправлено

4 - не исправлено

**Comment by yanna1986** [comment]
https://github.com/yanna1986/29-08-2020
 https://yanna1986.github.io/29-08-2020/
Добрый вечер!

ср, 9 сент. 2020 г. в 08:35, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
теперь отлично, принято.

ср, 9 вер. 2020 о 19:56 yanna1986 <notifications@github.com> пише:
